//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCSDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public string Ma { get; set; }
        public string Ten { get; set; }
        public decimal DonGia { get; set; }
        public string MaDanhMuc { get; set; }
    
        public virtual DanhMuc DanhMuc { get; set; }
    }
}
